server:
  port: 2333
  address: 0.0.0.0

lavalink:
  server:
    password: ""
    sources:
      youtube: false

plugins:
  youtube:
    oauth:
      enabled: true
      refreshToken: ""
      skipInitialization: true
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - TV
